/**
 * Generate typed query barrel files for a directory of SQL files.
 *
 * For each `queries/` directory containing `.sql` files, emits:
 * - `queries.generated.ts` — imports all SQL files and exports them as a record
 * - `queries.generated.d.ts` — declares the QueryMap interface with typed params/results
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, dirname, basename } from "node:path";
import { parseFrontMatter, type SqlFrontMatter } from "./parse-front-matter";
import { tableNameToTypeName } from "./generate-db-types";
import { validateSql } from "./validate-sql";
import { extractTypeReferences } from "./utils";

/**
 * Check if a result type string is a bare table name (no spaces, no special chars).
 * Bare table names get imported from db-types.d.ts.
 */
function isBareTableName(result: string): boolean {
  return /^[a-z][a-z0-9_]*$/.test(result);
}

/**
 * Generate the queries.generated.ts content (combined runtime + types).
 */
function generateBarrel(
  queryEntries: { name: string; data: SqlFrontMatter }[],
  tableNames: string[],
  dbTypesRelPath: string,
  modelRelPath: string | null,
  overrides: Record<string, string> = {},
): string {
  const header = `// AUTO-GENERATED by vite-plugin-sql-types — do not edit\n\n`;

  // Collect all type references (using PascalCase names for tables)
  const tableRefs = new Set<string>();
  const modelRefs = new Set<string>();

  for (const { data } of queryEntries) {
    // Check result type
    if (data.result) {
      if (isBareTableName(data.result)) {
        if (tableNames.includes(data.result)) {
          tableRefs.add(tableNameToTypeName(data.result, overrides));
        }
      } else {
        // Complex type expression — extract referenced type names
        for (const ref of extractTypeReferences(data.result)) {
          // Check if this ref matches a table name (case-insensitive check)
          const matchingTable = tableNames.find(
            (t) => tableNameToTypeName(t, overrides) === ref
          );
          if (matchingTable) {
            tableRefs.add(tableNameToTypeName(matchingTable, overrides));
          } else {
            modelRefs.add(ref);
          }
        }
      }
    }

    // Check param types
    if (data.params) {
      for (const typeExpr of Object.values(data.params)) {
        for (const ref of extractTypeReferences(typeExpr)) {
          const matchingTable = tableNames.find(
            (t) => tableNameToTypeName(t, overrides) === ref
          );
          if (matchingTable) {
            tableRefs.add(tableNameToTypeName(matchingTable, overrides));
          } else {
            modelRefs.add(ref);
          }
        }
      }
    }
  }

  // Build type import statements
  const typeImports: string[] = [];

  if (tableRefs.size > 0) {
    const tableImportList = [...tableRefs].sort().join(", ");
    typeImports.push(`import type { ${tableImportList} } from "${dbTypesRelPath}";`);
  }

  if (modelRefs.size > 0 && modelRelPath) {
    const modelImportList = [...modelRefs].sort().join(", ");
    typeImports.push(`import type { ${modelImportList} } from "${modelRelPath}";`);
  }

  // Build QueryMap interface
  const mapEntries = queryEntries.map(({ name, data }) => {
    const paramsType = data.params
      ? `{ ${Object.entries(data.params).map(([k, v]) => `${k}: ${v}`).join("; ")} }`
      : "{}";

    let resultType: string;
    if (!data.result) {
      resultType = "Record<string, unknown>";
    } else if (data.result === "void") {
      resultType = "void";
    } else if (isBareTableName(data.result)) {
      // Convert bare table name to PascalCase type name
      resultType = tableNameToTypeName(data.result, overrides);
    } else {
      // Complex type expression — convert any table name references to PascalCase
      resultType = data.result;
      for (const tableName of tableNames) {
        const pascalName = tableNameToTypeName(tableName, overrides);
        // Replace table name references in the type expression
        // This handles cases like "tenets & { extra: string }" → "Tenet & { extra: string }"
        resultType = resultType.replace(
          new RegExp(`\\b${tableName}\\b`, "g"),
          pascalName
        );
      }
    }

    return `  ${name}: {\n    params: ${paramsType};\n    result: ${resultType};\n  };`;
  });

  const queryMapInterface = `export interface QueryMap {\n${mapEntries.join("\n")}\n}`;

  // Build runtime code
  const helper = `/** Strip YAML front matter from SQL files at runtime. */
function stripFrontMatter(sql: string): string {
  // Handle BOM, leading whitespace, and different line endings (\\n or \\r\\n)
  const cleaned = sql.replace(/^\\ufeff/, "").trimStart();
  
  // Match front matter with flexible line endings
  const match = cleaned.match(/^---[\\r\\n]+[\\s\\S]*?[\\r\\n]+---[\\r\\n]+([\\s\\S]*)$/);
  
  if (!match) {
    // No front matter or malformed — return as-is
    return cleaned.trim();
  }
  
  return match[1].trim();
}`;

  const queryNames = queryEntries.map((e) => e.name);
  const sqlImports = queryNames
    .map((name) => `import ${name}Raw from "./${name}.sql?raw";`)
    .join("\n");

  const entries = queryNames
    .map((name) => `  ${name}: stripFrontMatter(${name}Raw),`)
    .join("\n");
  const queriesConst = `export const queries = {\n${entries}\n} as const;`;

  // Order: header, type imports, sql imports, QueryMap interface, helper, queries const
  return `${header}${typeImports.join("\n")}\n\n${sqlImports}\n\n${queryMapInterface}\n\n${helper}\n\n${queriesConst}\n`;
}

/**
 * Generate barrel files for a single queries directory.
 *
 * @param queriesDir — absolute path to the queries/ directory
 * @param tableNames — list of all known table names (from db-types)
 * @param dbTypesPath — absolute path to db-types.d.ts
 * @param modelPath — absolute path to the model.ts file (if it exists), or null
 * @param overrides — optional map of table names to custom type names
 */
export async function generateQueryBarrel(
  queriesDir: string,
  tableNames: string[],
  dbTypesPath: string,
  modelPath: string | null,
  overrides: Record<string, string> = {},
): Promise<void> {
  const files = (await readdir(queriesDir))
    .filter((f) => f.endsWith(".sql"))
    .sort();

  if (files.length === 0) return;

  const queryEntries: { name: string; data: SqlFrontMatter; sql: string }[] = [];

  for (const file of files) {
    const content = await readFile(join(queriesDir, file), "utf-8");
    const { data, sql } = parseFrontMatter(content, `${file}`);
    const name = basename(file, ".sql");
    queryEntries.push({ name, data, sql });
  }

  // Collect known types for validation
  const knownTypes = new Set<string>();
  
  // Add table types (PascalCase)
  for (const tableName of tableNames) {
    knownTypes.add(tableNameToTypeName(tableName, overrides));
  }
  
  // Add model types (if model.ts exists)
  if (modelPath) {
    try {
      const modelContent = await readFile(modelPath, "utf-8");
      // Extract exported type/interface names
      const typeRegex = /export\s+(?:type|interface)\s+(\w+)/g;
      let match: RegExpExecArray | null;
      while ((match = typeRegex.exec(modelContent)) !== null) {
        knownTypes.add(match[1]);
      }
    } catch {
      // Model file doesn't exist or can't be read — skip
    }
  }

  // Validate each SQL file
  for (const { name, data, sql } of queryEntries) {
    const validation = validateSql(sql, data, knownTypes);
    
    if (!validation.valid) {
      for (const error of validation.errors) {
        console.error(`✗ ${name}.sql: ${error}`);
      }
    }
    
    for (const warning of validation.warnings) {
      console.warn(`⚠ ${name}.sql: ${warning}`);
    }
  }

  const queryNames = queryEntries.map((e) => e.name);

  // Compute relative paths from the queries directory
  const dbTypesRelPath = relative(queriesDir, dbTypesPath).replace(/\.d\.ts$/, "");
  const modelRelPath = modelPath
    ? relative(queriesDir, modelPath).replace(/\.ts$/, "")
    : null;

  // Generate combined barrel (.ts with both runtime code and types)
  const barrelContent = generateBarrel(
    queryEntries,
    tableNames,
    dbTypesRelPath,
    modelRelPath,
    overrides,
  );
  await writeFile(join(queriesDir, "queries.generated.ts"), barrelContent, "utf-8");
}
