/**
 * Generate TypeScript type declarations from parsed SQLite table definitions.
 *
 * Emits a `.d.ts` file with:
 * - One interface per table (PascalCase singular name, e.g., `tenets` → `Tenet`)
 * - A `Database` interface mapping table names to their row types
 * - A `declare module "*.sql"` block for SQL file imports
 */

import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import type { TableDef, ColumnDef } from "./parse-migrations";

/**
 * Convert a table name to PascalCase singular form.
 * Examples: `tenets` → `Tenet`, `tenet_options` → `TenetOption`, `users` → `User`
 * 
 * @param tableName - The database table name (e.g., "tenets", "user_profiles")
 * @param overrides - Optional map of table names to custom type names (e.g., { "people": "Person" })
 */
export function tableNameToTypeName(
  tableName: string,
  overrides: Record<string, string> = {}
): string {
  // Check for explicit override first
  if (overrides[tableName]) {
    return overrides[tableName];
  }

  // Split by underscore, capitalize each part, join
  const pascalCase = tableName
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

  // Singularize
  return singularize(pascalCase);
}

/**
 * Simple singularization for English words.
 * Handles common patterns: -s, -es, -ies, -ves, -oes, -sses
 * 
 * Limitations:
 * - Irregular plurals (mice, geese, children, people) require tableNameOverrides
 * - Latin/Greek roots (data → datum, criteria → criterion) require tableNameOverrides
 */
function singularize(word: string): string {
  // Don't singularize if already singular-looking (ends with 'ss', 'us', 'is')
  if (word.endsWith("ss") || word.endsWith("us") || word.endsWith("is")) {
    return word;
  }

  // -ies → -y (e.g., Categories → Category)
  if (word.endsWith("ies")) {
    return word.slice(0, -3) + "y";
  }

  // -ves → -f (e.g., Wolves → Wolf, Knives → Knife)
  if (word.endsWith("ves")) {
    return word.slice(0, -3) + "f";
  }

  // -sses → -ss (e.g., Addresses → Address, Classes → Class)
  if (word.endsWith("sses")) {
    return word.slice(0, -2);
  }

  // -ses, -xes, -zes, -ches, -shes → remove 'es'
  if (
    word.endsWith("ses") ||
    word.endsWith("xes") ||
    word.endsWith("zes") ||
    word.endsWith("ches") ||
    word.endsWith("shes")
  ) {
    return word.slice(0, -2);
  }

  // -oes → -o (e.g., Potatoes → Potato, Tomatoes → Tomato)
  if (word.endsWith("oes")) {
    return word.slice(0, -2);
  }

  // -s → remove 's' (default case)
  if (word.endsWith("s")) {
    return word.slice(0, -1);
  }

  return word;
}

/** Map SQLite column types to TypeScript types. */
function sqliteTypeToTs(sqliteType: string): string {
  switch (sqliteType.toUpperCase()) {
    case "INTEGER":
      return "number";
    case "TEXT":
      return "string";
    case "REAL":
      return "number";
    case "BLOB":
      return "ArrayBuffer";
    default:
      return "unknown";
  }
}

/** Determine the TypeScript type for a column. */
function columnToTsType(col: ColumnDef): string {
  // CHECK IN values produce a string union type
  if (col.checkValues && col.checkValues.length > 0) {
    const union = col.checkValues.map((v) => `"${v}"`).join(" | ");
    // CHECK columns are always NOT NULL in practice (the CHECK constrains them)
    return col.notNull || col.isPrimaryKey ? union : `${union} | null`;
  }

  const baseType = sqliteTypeToTs(col.sqliteType);

  // PRIMARY KEY columns are never null
  if (col.isPrimaryKey) return baseType;

  // Columns without NOT NULL are nullable
  if (!col.notNull) return `${baseType} | null`;

  return baseType;
}

/** Generate the TypeScript interface for a single table. */
function generateTableInterface(
  table: TableDef,
  overrides: Record<string, string> = {}
): string {
  const typeName = tableNameToTypeName(table.name, overrides);
  const lines = table.columns.map((col) => {
    const tsType = columnToTsType(col);
    return `  ${col.name}: ${tsType};`;
  });

  return `export interface ${typeName} {\n${lines.join("\n")}\n}`;
}

/** Generate the full db-types.d.ts content. */
export function generateDbTypesContent(
  tables: TableDef[],
  overrides: Record<string, string> = {}
): string {
  const header = `/* AUTO-GENERATED by vite-plugin-sql-types — do not edit */\n`;

  const interfaces = tables
    .map((t) => generateTableInterface(t, overrides))
    .join("\n\n");

  const dbEntries = tables
    .map((t) => `  ${t.name}: ${tableNameToTypeName(t.name, overrides)};`)
    .join("\n");
  const dbInterface = `export interface Database {\n${dbEntries}\n}`;

  const sqlModule = `declare module "*.sql" {\n  const sql: string;\n  export default sql;\n}`;

  return `${header}\n${interfaces}\n\n${dbInterface}\n\n${sqlModule}\n`;
}

/** Write the generated db-types.d.ts to disk. */
export async function generateDbTypes(
  tables: TableDef[],
  outputPath: string,
  overrides: Record<string, string> = {}
): Promise<void> {
  const content = generateDbTypesContent(tables, overrides);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content, "utf-8");
}
