/**
 * Generate TypeScript model interfaces from a SchemaDef.
 *
 * Emits a `.d.ts` file with:
 * - One interface per table (PascalCase singular name, e.g., `tenets` → `Tenet`)
 * - A `Database` interface mapping table names to their row types
 * - A `declare module "*.sql"` block for SQL file imports
 *
 * This replaces the old SQL-parse→types path: types are now derived directly
 * from the TypeScript schema definition.
 */

import type { SchemaDef, ColumnDef, SqliteType } from "./schema-def";

/** Convert a table name to PascalCase singular form (same rules as before). */
export function tableNameToTypeName(
  tableName: string,
  overrides: Record<string, string> = {},
): string {
  if (overrides[tableName]) return overrides[tableName];

  const pascalCase = tableName
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

  return singularize(pascalCase);
}

/** Simple singularization for English words (ported from the SQL typegen). */
function singularize(word: string): string {
  if (word.endsWith("ss") || word.endsWith("us") || word.endsWith("is")) {
    return word;
  }
  if (word.endsWith("ies")) return word.slice(0, -3) + "y";
  if (word.endsWith("ives")) return word.slice(0, -4) + "ife";
  if (word.endsWith("ves")) return word.slice(0, -3) + "f";
  if (word.endsWith("sses")) return word.slice(0, -2);
  if (
    word.endsWith("ses") ||
    word.endsWith("xes") ||
    word.endsWith("zes") ||
    word.endsWith("ches") ||
    word.endsWith("shes")
  ) {
    return word.slice(0, -2);
  }
  if (word.endsWith("oes")) return word.slice(0, -2);
  if (word.endsWith("s")) return word.slice(0, -1);
  return word;
}

/** Map SQLite column types to TypeScript types. */
function sqliteTypeToTs(sqliteType: SqliteType): string {
  switch (sqliteType) {
    case "INTEGER":
      return "number";
    case "TEXT":
      return "string";
    case "REAL":
      return "number";
    case "BLOB":
      return "ArrayBuffer";
  }
}

/** Determine the TypeScript type for a column. */
function columnToTsType(col: ColumnDef): string {
  if (col.checkValues && col.checkValues.length > 0) {
    const union = col.checkValues.map((v) => `"${v}"`).join(" | ");
    // CHECK columns are always NOT NULL in practice (the CHECK constrains them).
    return col.notNull || col.primaryKey ? union : `${union} | null`;
  }

  const baseType = sqliteTypeToTs(col.sqliteType);

  // PRIMARY KEY columns are never null.
  if (col.primaryKey) return baseType;

  // Columns without NOT NULL are nullable.
  if (!col.notNull) return `${baseType} | null`;

  return baseType;
}

function generateTableInterface(
  table: SchemaDef["tables"][number],
  overrides: Record<string, string>,
): string {
  const typeName = tableNameToTypeName(table.name, overrides);
  const lines = table.columns.map((col) => {
    const tsType = columnToTsType(col);
    return `  ${col.name}: ${tsType};`;
  });

  return `export interface ${typeName} {\n${lines.join("\n")}\n}`;
}

/** Generate the full db-types.d.ts content from a SchemaDef. */
export function generateDbTypesContent(
  schema: SchemaDef,
  overrides: Record<string, string> = {},
): string {
  const header = `/* AUTO-GENERATED by js-mvc/schema — do not edit */\n`;

  const interfaces = schema.tables
    .map((t) => generateTableInterface(t, overrides))
    .join("\n\n");

  const dbEntries = schema.tables
    .map((t) => `  ${t.name}: ${tableNameToTypeName(t.name, overrides)};`)
    .join("\n");
  const dbInterface = `export interface Database {\n${dbEntries}\n}`;

  const sqlModule = `declare module "*.sql" {\n  const sql: string;\n  export default sql;\n}`;

  return `${header}\n${interfaces}\n\n${dbInterface}\n\n${sqlModule}\n`;
}
