/* AUTO-GENERATED by vite-plugin-sql-types — do not edit */

export interface User {
  id: number;
  github_id: number;
  login: string;
  avatar_url: string | null;
  name: string | null;
  created_at: string;
  last_login_at: string;
}

export interface Tenet {
  id: number;
  title: string;
  slug: string;
  status: "draft" | "voting" | "accepted" | "rejected" | "implemented" | "superseded";
  context: string;
  decision: string | null;
  rationale: string | null;
  proposed_by_id: number;
  created_at: string;
  updated_at: string;
  superseded_by_id: number | null;
}

export interface TenetOption {
  id: number;
  tenet_id: number;
  title: string;
  description: string | null;
  pros: string | null;
  cons: string | null;
  sort_order: number;
}

export interface Vote {
  id: number;
  tenet_id: number;
  user_id: number;
  choice: "approve" | "abstain" | "block";
  reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface Database {
  users: User;
  tenets: Tenet;
  tenet_options: TenetOption;
  votes: Vote;
}

declare module "*.sql" {
  const sql: string;
  export default sql;
}
