import type { Plugin } from "vite";
import { resolve, dirname, join } from "path";
import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { pathToFileURL } from "node:url";
import { generateQueryBarrel } from "./sql-types";
import type { SchemaDef } from "../src/schema/schema-def";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Recursively find all .sql files under a root path and group them
 * by their parent directory. Excludes generated files and init.sql.
 *
 * Returns a Map of directory path → sorted .sql file names.
 */
async function findSqlFileGroups(
  root: string,
  excludePatterns: string[] = [".generated", "init.sql"],
): Promise<Map<string, string[]>> {
  const groups = new Map<string, string[]>();

  async function walk(dir: string): Promise<void> {
    let entries: import("node:fs").Dirent[];
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!entry.name.startsWith(".") && entry.name !== "node_modules") {
          await walk(fullPath);
        }
      } else if (
        entry.isFile() &&
        entry.name.endsWith(".sql") &&
        !excludePatterns.some((p) => entry.name.includes(p) || entry.name === p)
      ) {
        const parent = dir;
        const existing = groups.get(parent);
        if (existing) {
          existing.push(entry.name);
        } else {
          groups.set(parent, [entry.name]);
        }
      }
    }
  }

  await walk(root);

  for (const [, files] of groups) {
    files.sort();
  }

  return groups;
}

/**
 * Recursively hash all .sql files under a directory to detect changes.
 * Returns a SHA-256 hash of all file contents.
 */
async function hashDirectory(
  dir: string,
  excludePatterns: string[] = [".generated", "init.sql"],
): Promise<string> {
  const hash = createHash("sha256");

  async function walk(currentDir: string): Promise<void> {
    let entries: import("node:fs").Dirent[];
    try {
      entries = await readdir(currentDir, { withFileTypes: true });
    } catch {
      return;
    }

    const sqlFiles = entries
      .filter(
        (f) =>
          f.isFile() &&
          f.name.endsWith(".sql") &&
          !excludePatterns.some((p) => f.name.includes(p) || f.name === p),
      )
      .map((f) => f.name)
      .sort();

    for (const file of sqlFiles) {
      const content = await readFile(join(currentDir, file), "utf-8");
      hash.update(content);
    }

    for (const entry of entries) {
      if (
        entry.isDirectory() &&
        !entry.name.startsWith(".") &&
        entry.name !== "node_modules"
      ) {
        await walk(join(currentDir, entry.name));
      }
    }
  }

  await walk(dir);
  return hash.digest("hex");
}

// ---------------------------------------------------------------------------
// Cache
// ---------------------------------------------------------------------------

interface GenerationCache {
  barrelHashes: Map<string, string>;
}

function createCache(): GenerationCache {
  return { barrelHashes: new Map() };
}

function clearCache(cache: GenerationCache): void {
  cache.barrelHashes.clear();
}

// ---------------------------------------------------------------------------
// Generation pipeline
// ---------------------------------------------------------------------------

export interface SqlTypesPluginOptions {
  /**
   * Path to the TypeScript schema module generated by schemaPlugin.
   * Query-barrel generation reads table names from this module so it stays
   * driven by the TS schema source of truth rather than migration SQL.
   * @default "src/.generated/schema.ts"
   */
  schemaModulePath?: string;

  /**
   * Path to the data directory containing .sql query files (relative to project root or absolute).
   * @default "src/domains"
   */
  dataDir?: string;

  /**
   * Output path for the generated db-types.d.ts file.
   * @default "src/domains/db-types.d.ts"
   */
  dbTypesPath?: string;

  /**
   * Name of the model file to look for in parent directories of .sql files.
   * @default "model.ts"
   */
  modelFileName?: string;

  /**
   * Override automatic table name to type name conversions.
   * Map of table names (as they appear in the database) to desired TypeScript type names.
   *
   * @example
   * {
   *   "people": "Person",
   *   "children": "Child",
   *   "user_profiles": "UserProfile"
   * }
   */
  tableNameOverrides?: Record<string, string>;

  /**
   * Patterns to exclude when scanning for .sql files.
   * @default [".generated", "init.sql"]
   */
  sqlExcludePatterns?: string[];
}

interface ResolvedPaths {
  schemaModulePath: string;
  dataDir: string;
  dbTypesPath: string;
  modelFileName: string;
  sqlExcludePatterns: string[];
}

function resolvePaths(
  projectRoot: string,
  options: SqlTypesPluginOptions,
): ResolvedPaths {
  const toAbsolute = (p: string | undefined, fallback: string) =>
    p && p.startsWith("/") ? p : resolve(projectRoot, p ?? fallback);

  return {
    schemaModulePath: toAbsolute(options.schemaModulePath, "src/.generated/schema.ts"),
    dataDir: toAbsolute(options.dataDir, "src/domains"),
    dbTypesPath: toAbsolute(options.dbTypesPath, "src/domains/db-types.d.ts"),
    modelFileName: options.modelFileName ?? "model.ts",
    sqlExcludePatterns: options.sqlExcludePatterns ?? [
      ".generated",
      "init.sql",
    ],
  };
}

/**
 * Read the list of table names from the generated schema module
 * (written by schemaPlugin from the TS schema source of truth).
 */
async function readTableNamesFromSchemaModule(
  schemaModulePath: string,
): Promise<string[]> {
  const mod = (await import(pathToFileURL(resolve(schemaModulePath)).href + `?t=${Date.now()}`)) as {
    schemaDef: SchemaDef;
  };
  return mod.schemaDef.tables.map((t) => t.name);
}

/**
 * Run query-barrel generation for `.sql` query files.
 *
 * Table names (needed to resolve bare table-name result types to model
 * interfaces) are read from the TS-schema-generated module, so the whole
 * typing pipeline stays driven by the TypeScript source of truth rather
 * than parsed migration SQL.
 */
async function runSqlTypeGeneration(
  paths: ResolvedPaths,
  tableNameOverrides: Record<string, string>,
  cache: GenerationCache,
): Promise<string[]> {
  const tableNames = await readTableNamesFromSchemaModule(paths.schemaModulePath);
  const schemaSalt = await hashSchemaModule(paths.schemaModulePath);

  const sqlFileGroups = await findSqlFileGroups(
    paths.dataDir,
    paths.sqlExcludePatterns,
  );

  for (const [queriesDir] of sqlFileGroups) {
    const dirHash = await hashDirectory(queriesDir, paths.sqlExcludePatterns);
    const barrelHash = `${dirHash}:${schemaSalt}`;
    const cachedHash = cache.barrelHashes.get(queriesDir);

    if (cachedHash === barrelHash) {
      console.log(
        `✓ Using cached barrel for ${queriesDir.split("/").slice(-2).join("/")}`,
      );
      continue;
    }

    const parentDir = dirname(queriesDir);
    const modelPath = join(parentDir, paths.modelFileName);
    const modelFile = existsSync(modelPath) ? modelPath : null;

    try {
      await generateQueryBarrel(
        queriesDir,
        tableNames,
        paths.dbTypesPath,
        modelFile,
        tableNameOverrides,
      );
      cache.barrelHashes.set(queriesDir, barrelHash);
    } catch (e) {
      throw new Error(
        `Failed to generate barrel for ${queriesDir}: ${(e as Error).message}`,
      );
    }
  }

  return tableNames;
}

/** Hash the generated schema module so barrels rebuild when the schema changes. */
async function hashSchemaModule(schemaModulePath: string): Promise<string> {
  return createHash("sha256")
    .update(await readFile(schemaModulePath, "utf-8"))
    .digest("hex");
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

/**
 * Vite plugin for typed SQL query barrels.
 *
 * - Generates typed query barrels for each `queries/` directory, resolving
 *   bare table-name result types from the schema module generated by
 *   `schemaPlugin`, so the typing pipeline stays driven by the TS schema
 *   source of truth
 * - Watches for `.sql` query-file changes in dev mode and regenerates
 *
 * Note: YAML front matter stripping is handled by `sqlTransformPlugin`.
 * Model types and the derived schema.sql are produced by `schemaPlugin`.
 */
export function sqlTypesPlugin(options: SqlTypesPluginOptions = {}): Plugin {
  let projectRoot: string;
  let resolvedPaths: ResolvedPaths;
  const cache = createCache();

  return {
    name: "sql-types",
    enforce: "pre",

    configResolved(config) {
      projectRoot = config.root;
      resolvedPaths = resolvePaths(projectRoot, options);
    },

    async buildStart() {
      console.log("🗄️  Generating SQL types...");
      clearCache(cache);
      try {
        await runSqlTypeGeneration(
          resolvedPaths,
          options.tableNameOverrides ?? {},
          cache,
        );
        console.log("✓ SQL types generated");
      } catch (e) {
        console.error("✗ SQL type generation failed:", (e as Error).message);
      }
    },

    configureServer(server) {
      server.watcher.add(resolvedPaths.dataDir);

      let regenerationTimeout: ReturnType<typeof setTimeout> | null = null;
      const DEBOUNCE_MS = 100;

      const debouncedRegenerate = (
        _file: string,
        regenerate: () => Promise<void>,
      ) => {
        if (regenerationTimeout) {
          clearTimeout(regenerationTimeout);
        }

        regenerationTimeout = setTimeout(async () => {
          try {
            await regenerate();
          } catch (e) {
            console.error(
              "✗ SQL type generation failed:",
              (e as Error).message,
            );
          }
        }, DEBOUNCE_MS);
      };

      server.watcher.on("change", async (file: string) => {
        // Regenerate barrel on query file changes
        if (
          file.startsWith(resolvedPaths.dataDir) &&
          file.endsWith(".sql") &&
          !resolvedPaths.sqlExcludePatterns.some((p) => file.includes(p))
        ) {
          console.log(
            `\n🗄️  Query changed: ${file.split("/").pop()}, regenerating barrel...`,
          );
          debouncedRegenerate(file, async () => {
            const tableNames =
              await readTableNamesFromSchemaModule(resolvedPaths.schemaModulePath);

            const queriesDir = dirname(file);
            const parentDir = dirname(queriesDir);
            const modelPath = join(parentDir, resolvedPaths.modelFileName);
            const modelFile = existsSync(modelPath) ? modelPath : null;

            await generateQueryBarrel(
              queriesDir,
              tableNames,
              resolvedPaths.dbTypesPath,
              modelFile,
              options.tableNameOverrides ?? {},
            );
            console.log("✓ Query barrel regenerated\n");
          });
        }
      });

      // Clean up debounce timeout when server shuts down
      server.httpServer?.on("close", () => {
        if (regenerationTimeout) {
          clearTimeout(regenerationTimeout);
          regenerationTimeout = null;
        }
      });
    },
  };
}
